### ISSUE TITLE
Address Conf

### ISSUE THREAD

**Issue by pierre-sigwalt** [danielgafni/dagster-ray#113]
I have setup Dagster ray with the .yaml such as:

```yaml
run_launcher:
  module: dagster_ray
  class: RayRunLauncher
  config:
    ray:
      address: http://127.0.0.1:8265
      num_cpus: 1
      runtime_env:
      env_vars:
        - DAGSTER_POSTGRES_USER
        - DAGSTER_POSTGRES_PASSWORD
        - DAGSTER_POSTGRES_DB

telemetry:
  enabled: false
```

the process is running using Dagster Dev.

However I am getting the following error:

pydantic_core._pydantic_core.ValidationError: 1 validation error for RayLauncherConfig
address
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]

thank you
